runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*  # This regex directs all routes to main.app
  script: VitrasaBot.app
  secure: always

libraries:
- name: ssl
  version: latest
- name: webapp2
  version: "2.5.2"
